✨ Add new painter example
mcbookshelf/bookshelf pull request #198
Opened 2024-05-25 14:41 UTC by aksiome

2025-03-08 13:12 UTC, theogiraudet requested changes

2025-03-08 13:12 UTC, theogiraudet commented on examples/paintbrush.md
> +
Perhaps we should add a download to an empty datapack template to quick start, or a "- a ready-to-use empty datapack"?
Because we directly start by "create a function".

2025-03-08 13:12 UTC, theogiraudet commented on examples/paintbrush.md
> +3. Generate the final result, which can be a block, item, particle, block display, etc. (here, we’ll replace the block with its transformed version).
"Generate the final result from the virtual block, …"

2025-03-08 13:12 UTC, theogiraudet commented on examples/paintbrush.md
> +- `bs.shapes`: This registry is used to transform blocks based on their shape. For instance, if the held block is an oak plank, and the targeted block is a birch stair, this registry would map the oa
"oak plank**s**", "bich stair**s**"

2025-03-08 13:50 UTC, aksiome commented on examples/paintbrush.md
> +
Ideally a template would be best, could be what we talked about a few days ago (a template with beet and bookshelf preinstalled). But I think it's out of this scope and something for later, also it may be too complex for small experimentation, so i'll just use a new bullet item for now

2025-03-15 16:21 UTC, theogiraudet approved these changes

2025-03-15 16:21 UTC, merged