Add a new `bs.string` module
mcbookshelf/bookshelf pull request #283
Opened 2024-11-30 12:45 UTC by aure31

# Tasks to do before merging
- [ ] I accept to publish my contribution under [MPL v2](http://mozilla.org/MPL/2.0/) License
- [ ] My pull request is linked to an existing issue
- [ ] I have added my contribution to the [changelog](https://github.com/Gunivers/Bookshelf/blob/master/docs/CHANGELOG.md)
- If my pull request is a new or modify an existing feature:
  - [ ] I have documented my contribution (`/docs`)
  - [ ] I have added or updated the [header](https://bookshelf.docs.gunivers.net/en/latest/contribute/file-format.html) of the features' root function I contribute
  - [ ] I have [tested](https://bookshelf.docs.gunivers.net/en/latest/contribute/debug.html#unit-tests) my contribution

2024-11-30 19:42 UTC, aure31 commented
close #191

2025-01-17 13:09 UTC, aksiome reviewed
Hey really quick review before this gets too big. I have'nt reviewed everything but it's a start

2025-01-17 13:09 UTC, aksiome commented on modules/bs.string/data/bs.string/function/concat/dispatch.mcfunction
Im not sure you understood completly what i was going for with this. Using the current implementation there is no benefit from the macro cache since the function is called with any length. The whole point was to create small chunks of 8 to avoid cache miss. Also I was maybe a bit wrong and it's better to scale this up to a cache of 8 by 8. Which means going up to 64 before using powers of 2. If you're not sure about it don't worry to much i already have a pretty good idea of the implementation so i can take care of it

2025-01-17 13:09 UTC, aksiome commented on modules/bs.string/data/bs.string/function/lower_case/fast/loop.mcfunction
Im not sure we need a fast and slow behavior. This come from the fact that the table is a list and you use filtering. But having one way tables (`{a:A,b:B}`) for uppercase to lowercase and lowercase to uppercase would just simplify all this and actually bring even more performance since they are simple hashmap with no filtering

2025-01-17 13:09 UTC, aksiome commented on modules/bs.string/data/bs.string/function/upper_case/fast/loop.mcfunction
same as for lowercase. Also i think upper and lower are clear enough, no need for lower_case and upper_case

2025-01-17 14:48 UTC, aure31 commented on meta/versions.json
normaly resolved I think it's was during the merge or when I try to update the meta my fault sorry

2025-01-17 14:51 UTC, aure31 commented on modules/bs.string/data/bs.string/function/concat/dispatch.mcfunction
I’ve made some changes, but I’m not sure if they align with what you had in mind. If that’s not the case, could you please clarify? I’d really like to understand your perspective.

2025-01-17 16:41 UTC, aure31 commented on modules/bs.string/data/bs.string/function/concat/dispatch.mcfunction
So if I understand right, the minecraft cache work with 8 values for each file with the macro so all the value between 0 and 64 here. Is that right ? I would like to make a call to explain me how the cache system work if you can.

2025-01-17 18:03 UTC, aksiome commented on modules/bs.string/data/bs.string/function/concat/dispatch.mcfunction
Yeah minecraft can cache up to 8 different macro functions. For example with these inputs you'll have 3 functions in cache:
- `{a:1,b:0}`
- `{a:0,b:1}`
- `{a:1,b:1}` even if a:1 already exist b is different. It works using the full set of inputs not just a single value

That's also why sometimes it's better to split these macro inputs between multiple function by using a function tag as we do in some modules. This way you get a bit of extra cache.

After 8 different functions are stored in cache the oldest gets deleted to let space for new ones. Also a function that is in cache will perform the same as a function with no macro.

2025-01-26 17:09 UTC, aksiome reviewed
Ok i'm really nitpicking here, i mainly reviewed the style and not the logic. For the logic I'll need more time to run the tests and all. Also there are some remaining say and tellraw, i'm sure it's because it's not completly finished and ready for the last review, but i commented some of them (not all). A small cleanup cannot hurt i guess 👍

2025-01-26 17:09 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/find.mcfunction
> +$scoreboard players set #bs.string.occurrence bs.data $(occurrence)
no need to use bs.data can be bs.ctx if the function does not "leak" into user territory (with a callback) or with other functions from other modules

2025-01-26 17:09 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/find.mcfunction
> +execute store result score #l bs.ctx run data get storage bs:in string.find.str
same as before to get the len

2025-01-26 17:09 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/inverse/inverse.mcfunction
> +say inverse
remaining say

2025-01-26 17:09 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/inverse/up.mcfunction
missing header

2025-01-26 17:09 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/precompute.mcfunction
> +# ------------------------------------------------------------------------------------------------------------
missing new line

2025-01-26 17:09 UTC, aksiome commented on modules/bs.string/templates/concat.jinja
The 2 templates are outputting an extra line after the header, also adding a comment like this `# This file was automatically generated, do not edit it` at the start might be a good thing, see the templates from the block module for reference

2025-01-26 18:50 UTC, aure31 commented on modules/bs.string/data/bs.string/function/find/find.mcfunction
> +execute store result score #l bs.ctx run data get storage bs:in string.find.str
with the if data ? because it's doesn't work for me it's juste store the success and not the len

2025-01-26 18:52 UTC, aure31 commented on modules/bs.string/data/bs.string/function/find/inverse/up.mcfunction
for the reversed I maybe will delete it. I d'ont what you think ? because I need to do a different precompute for it

2025-01-26 19:36 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/find.mcfunction
> +execute store result score #l bs.ctx run data get storage bs:in string.find.str
yeah with if data it works but you need [] at the end `if data storage path to.array[]`

2025-01-26 19:39 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/inverse/up.mcfunction
as you want, but yeah maybe a single direction is enough

2025-01-26 20:21 UTC, aure31 commented on modules/bs.string/data/bs.string/function/find/find.mcfunction
> +execute store result score #l bs.ctx run data get storage bs:in string.find.str
but it's a string not a list

2025-01-28 14:35 UTC, aure31 commented on docs/modules/string.md
> +  - {nbt}`compound` Arguments
with what I replace it ?

2025-01-28 16:13 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/find.mcfunction
> +execute store result score #l bs.ctx run data get storage bs:in string.find.str
Yeah sorry, it's only for concat. Did too much python haha 😅

2025-01-28 17:35 UTC, aure31 commented on docs/modules/string.md
> +**`#bs.string:help`**
how you find the image for the module with a black and white variant

2025-01-28 17:54 UTC, aksiome commented on docs/modules/string.md
> +**`#bs.string:help`**
Either have a png with transparent background, or make 2 versions. If you don't really feel like doing some image design we'll try to do it (either Theo or me)

2025-03-02 19:12 UTC, aksiome requested changes
Globally i think we should avoid mixing storage and macro. This is because it's really hard to tell if some parameters are to be used dynamically or not. For example occurence may be used with a constant value but some people might want to use it dynamically and it adds extra complexity. I think we should only use storage for the whole module. Also some tests are failing, and i think some function could be changed a bit. Here are my propositions:

- find should be renamed find_all (still returns a list) and we should have a simple find that returns only the first occurence as an int from the function. This mean that the command can easily be used with if function.
- insert can be reworked easily into something like replace_range / substr_replace which does the same and more with a similar implementation (see the details after)

2025-03-02 19:12 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/normal/normal.mcfunction
> +execute if score #t bs.ctx matches 0 run return run function bs.string:find/normal/skip with storage bs:ctx
Not really needed since we're calling skip either way right?

2025-03-02 19:12 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/normal/normal.mcfunction
> +data modify storage bs:ctx z set from storage bs:ctx y
no need to copy this value, directly use y instead of z inside skip

2025-03-02 19:12 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/normal/skip.mcfunction
> +$execute store result storage bs:ctx x int 1 run scoreboard players add #i bs.ctx $(z)
As said in find, it's better to only work with score and only copy to out storage when something is found

2025-03-02 19:12 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/count/up.mcfunction
> +data modify storage bs:out string.find append from storage bs:ctx x
As said after in find avoid using x and use the score instead

2025-03-02 19:12 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/count/count.mcfunction
> +data modify storage bs:ctx z set from storage bs:ctx y
not needed directly use y directly in match_pattern instead

2025-03-02 19:12 UTC, aksiome commented on modules/bs.string/data/bs.string/function/find/count/skip.mcfunction
> +
Same as for normal/skip

2025-03-02 19:12 UTC, aksiome commented on modules/bs.string/data/bs.string/function/split/split.mcfunction
> +# ------------------------------------------------------------------------------------------------------------
missing new line. Also im lazy and i think a lot of code is shared with find, so i'll just say everything for find applies here

2025-03-02 19:12 UTC, aksiome commented on modules/bs.string/data/bs.string/function/replace/replace.mcfunction
> +#reset
comment style. Also im lazy so i'll just say that everything from find applies here

2025-03-08 12:43 UTC, aure31 commented on modules/bs.string/data/bs.string/function/insert/insert.mcfunction
> +
yes but it's relly less optimise because he need to check for the size who is always 3 so we lost performance for nothing

2025-03-08 13:00 UTC, aksiome commented on modules/bs.string/data/bs.string/function/insert/insert.mcfunction
> +
Sorry if i was unclear, i was not talking about using the concat function, i was saying we should copy the content of the bs.string:concat/combine/2c function into a dedicated concat function inside the insert folder

2025-03-22 19:43 UTC, theogiraudet requested changes

2025-03-22 19:43 UTC, theogiraudet commented on modules/bs.string/README.md
> +This module allows you to easily manage string in Minecraft.
This module allows you to easily manage strings in Minecraft.

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +
It could be interesting to add as a global limitation/warning the range of supported characters. I suppose you cannot lowercase an ancient-Greek letter for instance.

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +_Convert `hello world` to uppercase:_
The example must help the user to understand the feature, here you are not showing the expecting result so we cannot understand it if we don't know what "uppercase" means.
I suggest to modify this line by "Convert `hello world` to its uppercase version `HELLO WORLD`:" or something like this.

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +_Convert `HELLO WORLD` to lowercase:_
Same here

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +    - {nbt}`int` **occurrence**: Number of occurrences to find (0 for all).
Semantically, I'm not a big fan of "zero" as "all occurrences" because 0 means to search for no occurences, which even if this is a trivial case, it is semantically correct.
According to me, `-1` may be better because "-1 occurences" means nothing. This number is often use to say "no limit".
Do you have a reason for using 0 (an example in a language, optimization reason)?
If not, I suggest to use `-1` instead.

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +tellraw @a [{"text":"Found at indices: \""},{"storage":"bs:out","nbt":"string.find"},{"text":"\""}]
Put in comment the two expected results. We should be able to read the results without having to execute the command.

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +Replace occurrences of a substring with new text.
"Replace occurrences of a substring by a new text."

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +    - {nbt}`int` **maxreplace**: Maximum replacements. (0 for unlimited)
Same comment than before.

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +tellraw @a [{"text":"The new string is \""},{"storage":"bs:out","nbt":"string.replace_range"},{"text":"\""}]
Same than previous comment.

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +tellraw @a [{"text":"The reversed string is \""},{"storage":"bs:out","nbt":"string.reverse"},{"text":"\""}]
Same than previous comment.

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +    - {nbt}`int` **maxsplit**: Maximum number of splits to perform (0 or negative for unlimited).
Same than previous comment.

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +tellraw @a [{"text":"The list of strings is \""},{"storage":"bs:out","nbt":"string.split"},{"text":"\""}]
Same than previous comment.

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +Convert a string into a list where each character become a separate element.
"Convert a string into a list where each character become**s** a separate element."

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +tellraw @a [{"text":"The list of characters is \""},{"storage":"bs:out","nbt":"string.to_list"},{"text":"\""}]
Same than previous comment.

2025-03-22 19:43 UTC, theogiraudet commented on docs/modules/string.md
> +Convert any value into it's string representation.
"Convert any value into it**s** string representation."

2025-03-22 23:42 UTC, aure31 commented on docs/modules/string.md
> +
yes you can it's support all the utf8 table

2025-03-22 23:43 UTC, theogiraudet commented on docs/modules/string.md
> +
So it can be interesting to indicate that the module support all the UTF-8 table ;)

2025-03-23 10:03 UTC, aure31 commented on docs/modules/string.md
> +
do I put it into a admiton type hint after the technicall limitation ?
or somewhere else ?

2025-03-23 11:30 UTC, theogiraudet commented on docs/modules/string.md
> +
After technical limitation I think? @aksiome

2025-03-23 18:21 UTC, aksiome commented on docs/modules/string.md
> +
If we want to be really rigorous i think that the `"` limitation should be below every function that is concerned but not at the top. This is because it will actually just not work at all for uppercase and lowercase, since `\"` will be read as 2 characters (which is something we can easily fix). Also in find `\"` will also not be correctly read in the skip table so it's not gonna work at all. The only real limitation with this is when concatenating, and the problem is that find (and all other similar functions) use concatenation. This is why i think we should truly precise in each function what is the expected result when working with `"`, either we cant use them at all or we need to escape them

2025-03-23 18:23 UTC, aksiome commented on docs/modules/string.md
> +
And so to actually answer the question i think the precision about supported char should be inside the convert case section only imo. Because everything else is just minecraft

2025-03-23 19:00 UTC, aure31 commented on docs/modules/string.md
> +
I have change it but my phrase aren't good so tell me what I need to put

2025-03-27 21:50 UTC, theogiraudet requested changes

2025-03-27 21:50 UTC, theogiraudet commented on docs/modules/string.md
> +Due to the way string are handled, we don't support using `"` you need to use the `\"` instead.
"If you want to use double quotes (`"`) in a string, you need to escape them: `"\""`."
Is it also true for single quotes `'`? If yes, do we need to escape double quotes when we use single quotes and vice-versa?

2025-03-27 21:50 UTC, theogiraudet commented on docs/modules/string.md
> +this function actually support all UTF-8 characters so you can use it with any language.
"This function actually supports all UTF-8 characters."
I don't think we need to specify we "can use it with any language".

2025-03-28 06:15 UTC, aure31 commented on docs/modules/string.md
> +Due to the way string are handled, we don't support using `"` you need to use the `\"` instead.
No only double quote

2025-03-29 14:04 UTC, aksiome commented
Since we're gonna do some more changes on this module in #375. I propose to merge it as it is, and we'll improve the phrasing in #375 even if it's not super clean. I'll wait this evening in case someone is against this

2025-03-29 16:11 UTC, aksiome approved these changes

2025-03-29 16:11 UTC, merged